/* =================================================
   TRLOY js/07-export.js  (v3.4)
   P2 탭에서 호출되는 텍스트 빌더:
   1. buildDesignMdContent  → DESIGN.md 본문
   2. buildFigmaMakePrompt  → Figma Make 프롬프트
   3. buildStitchPrompt     → Stitch v2 프롬프트
   4. buildCursorRules      → .cursorrules
   5. buildClaudeCodePrompt → Claude Code 프롬프트
   + Quick Setup Snippets (tokensToTailwindConfig / tokensToCSSVariables)
   ================================================= */

/* -------------------------------------------------
   v1.0.1 파일명 규칙
   ------------------------------------------------- */
function vibeSlugFromTitle(title) {
  if (!title || typeof title !== 'string') return null;
  const slug = title.trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w가-힣ㄱ-ㅎㅏ-ㅣ-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return slug.slice(0, 40) || null;
}

function todayYMD() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

function buildDesignMdFilename(data) {
  const slug = vibeSlugFromTitle(data?.visualTheme?.title);
  return slug ? `${slug}-DESIGN.md` : `trloy-${todayYMD()}-DESIGN.md`;
}

/* -------------------------------------------------
   DESIGN.md 본문 생성
   섹션 구조 (§8.1):
   §1 Visual Theme & Atmosphere
   §2 Color Palette & Roles
   §3 Typography Rules
   §4 Component Stylings
   §5 Layout & Spacing
   §6 Depth & Elevation
   §7 Do's and Don'ts
   §8 Responsive Behavior
   §9 Agent Prompt Guide
   §10 Image Mood (TRLOY 확장)
   §11 Icon System (TRLOY 확장)
   §12 TRLOY Meta
   부록 Quick Setup Snippets
   ------------------------------------------------- */
function buildDesignMdContent(data) {
  const lines = [];
  const vt = data?.visualTheme || {};
  const cp = data?.colorPalette || {};
  const tp = data?.typography || {};
  const cm = data?.components || {};
  const lo = data?.layout || {};
  const de = data?.depth || {};
  const ru = data?.rules || {};
  const rs = data?.responsive || {};
  const ap = data?.agentPrompt || '';
  const ic = data?.iconSystem || {};
  const meta = data?.trloyMeta || {};
  const sn = data?.synthesisNote || {};

  lines.push(`# ${vt.title || 'DESIGN.md'}`);
  lines.push('');
  lines.push('> Generated by TRLOY — "Trace, Merge, Prompt"');
  lines.push(`> ${todayYMD()}`);
  lines.push('');

  /* §1 Visual Theme & Atmosphere */
  lines.push('## 1. Visual Theme & Atmosphere');
  lines.push('');
  if (vt.keywords?.length) lines.push(`**Keywords**: ${vt.keywords.join(' · ')}`);
  lines.push('');
  if (vt.atmosphere) lines.push(vt.atmosphere);
  lines.push('');

  /* §2 Color Palette */
  lines.push('## 2. Color Palette & Roles');
  lines.push('');
  lines.push('| Hex | Role | Meaning |');
  lines.push('|---|---|---|');
  (cp.colors || []).forEach((c) => {
    lines.push(`| \`${c.hex || ''}\` | ${c.role || ''} | ${c.meaning || ''} |`);
  });
  lines.push('');

  /* §2.1 Brand Colors (v3.31 확장) */
  if (cp.brand?.length) {
    lines.push('### Brand Colors');
    lines.push('');
    lines.push('| Name | Hex | Role | Meaning |');
    lines.push('|---|---|---|---|');
    cp.brand.forEach((c) => {
      lines.push(`| ${c.name || ''} | \`${c.hex || ''}\` | ${c.role || ''} | ${c.meaning || ''} |`);
    });
    lines.push('');
  }

  /* §2.2 Semantic Colors (v3.31 확장) */
  if (cp.semantic?.length) {
    lines.push('### Semantic Colors');
    lines.push('');
    lines.push('| Name | Hex | Role | Meaning |');
    lines.push('|---|---|---|---|');
    cp.semantic.forEach((c) => {
      lines.push(`| ${c.name || ''} | \`${c.hex || ''}\` | ${c.role || ''} | ${c.meaning || ''} |`);
    });
    lines.push('');
  }

  /* §3 Typography */
  lines.push('## 3. Typography Rules');
  lines.push('');
  lines.push('| Role | Family | Size | Weight | Line-height |');
  lines.push('|---|---|---|---|---|');
  ['display', 'heading', 'body', 'caption'].forEach((role) => {
    const s = tp[role];
    if (!s) return;
    lines.push(`| ${role} | ${s.family || ''} | ${s.size || ''} | ${s.weight ?? ''} | ${s.lineHeight || ''} |`);
  });
  lines.push('');

  /* §3.1 Typography Scale (v3.31 확장) */
  if (tp.scale?.length) {
    lines.push('### Full Typography Scale');
    lines.push('');
    lines.push('| Role | Family | Size | Weight | Line-height | Letter-spacing | Transform |');
    lines.push('|---|---|---|---|---|---|---|');
    tp.scale.forEach((t) => {
      lines.push(`| ${t.role || ''} | ${t.family || ''} | ${t.size || ''} | ${t.weight ?? ''} | ${t.lineHeight || ''} | ${t.letterSpacing || 'normal'} | ${t.textTransform || 'none'} |`);
    });
    lines.push('');
  }

  /* §4 Components */
  lines.push('## 4. Component Stylings');
  lines.push('');
  ['button', 'input', 'card'].forEach((name) => {
    const c = cm[name];
    if (!c) return;
    lines.push(`### ${name}`);
    lines.push('');
    Object.entries(c).forEach(([k, v]) => lines.push(`- **${k}**: ${v}`));
    lines.push('');
  });

  /* §4.1 Button Variants (v3.31 확장) */
  if (cm.buttonVariants?.length) {
    lines.push('### Button Variants');
    lines.push('');
    cm.buttonVariants.forEach((v) => {
      lines.push(`**${v.name || 'Variant'}**`);
      Object.entries(v).forEach(([k, val]) => {
        if (k !== 'name') lines.push(`- ${k}: ${val}`);
      });
      lines.push('');
    });
  }

  /* §5 Layout & Spacing */
  lines.push('## 5. Layout & Spacing');
  lines.push('');
  const layoutBasic = { grid: lo.grid, baseUnit: lo.baseUnit, gutter: lo.gutter, maxWidth: lo.maxWidth };
  Object.entries(layoutBasic).forEach(([k, v]) => {
    if (v !== undefined) lines.push(`- **${k}**: ${v}`);
  });
  if (lo.spacingScale?.length) {
    lines.push(`- **spacingScale**: ${lo.spacingScale.map((v) => v + 'px').join(', ')}`);
  }
  if (lo.radiusScale?.length) {
    lines.push(`- **radiusScale**: ${lo.radiusScale.join(', ')}`);
  }
  lines.push('');

  /* §6 Depth */
  lines.push('## 6. Depth & Elevation');
  lines.push('');
  (de.shadows || []).forEach((s) => lines.push(`- **${s.level}**: \`${s.value}\``));
  lines.push('');

  /* §7 Rules */
  lines.push("## 7. Do's and Don'ts");
  lines.push('');
  if (ru.dos?.length) {
    lines.push("### Do's");
    lines.push('');
    ru.dos.forEach((d) => lines.push(`- ${d}`));
    lines.push('');
  }
  if (ru.donts?.length) {
    lines.push("### Don'ts");
    lines.push('');
    ru.donts.forEach((d) => lines.push(`- ${d}`));
    lines.push('');
  }

  /* §8 Responsive */
  lines.push('## 8. Responsive Behavior');
  lines.push('');
  lines.push('| Name | Query | Cols |');
  lines.push('|---|---|---|');
  (rs.breakpoints || []).forEach((bp) => {
    lines.push(`| ${bp.name || ''} | ${bp.query || ''} | ${bp.cols ?? ''} |`);
  });
  lines.push('');

  /* §9 Agent Prompt */
  lines.push('## 9. Agent Prompt Guide');
  lines.push('');
  lines.push('```');
  lines.push(ap || '(empty)');
  lines.push('```');
  lines.push('');

  /* §10 Image Mood — 삭제됨 (v3.4) */

  /* §11 Icon System */
  lines.push('## 11. Icon System');
  lines.push('');
  ['style', 'weight', 'rounding'].forEach((k) => {
    if (ic[k] !== undefined) lines.push(`- **${k}**: ${ic[k]}`);
  });
  if (ic.library) {
    lines.push(`- **recommended**: ${ic.library.recommended || ''}`);
    if (ic.library.alternatives?.length)
      lines.push(`- **alternatives**: ${ic.library.alternatives.join(', ')}`);
  }
  if (ic.importCode) {
    lines.push('');
    lines.push('```');
    lines.push(ic.importCode);
    lines.push('```');
  }
  lines.push('');

  /* §12 TRLOY Meta */
  lines.push('## 12. TRLOY Meta');
  lines.push('');
  if (meta.designConcept) {
    lines.push('### 디자인 컨셉');
    lines.push('');
    lines.push(meta.designConcept);
    lines.push('');
  }
  if (meta.designPhilosophy) {
    lines.push('### 디자인 철학');
    lines.push('');
    lines.push(meta.designPhilosophy);
    lines.push('');
  }
  if (meta.emotions?.length) lines.push(`- **감정**: ${meta.emotions.join(' · ')}`);
  if (meta.target) lines.push(`- **타겟**: ${meta.target}`);
  if (meta.industry) lines.push(`- **업종**: ${meta.industry}`);
  if (meta.scenarios?.length) lines.push(`- **적용 시나리오**: ${meta.scenarios.join(' · ')}`);
  if (meta.position) lines.push(`- **포지션**: ${meta.position}`);
  lines.push('');

  /* Synthesis Note */
  lines.push('### 합성 노트 (4단계)');
  lines.push('');
  if (sn.commonExtraction) lines.push(`1. **공통 추출** — ${sn.commonExtraction}`);
  if (sn.differentiation) lines.push(`2. **차이 식별** — ${sn.differentiation}`);
  if (sn.prioritization) lines.push(`3. **우선순위** — ${sn.prioritization}`);
  if (sn.conflictResolution) lines.push(`4. **충돌 해소** — ${sn.conflictResolution}`);
  lines.push('');

  return lines.join('\n');
}

/* -------------------------------------------------
   Figma Make · Stitch 프롬프트 빌더
   (agentPrompt를 기반으로 도구별 포맷으로 래핑)
   ------------------------------------------------- */
function buildFigmaMakePrompt(data) {
  const vt = data?.visualTheme || {};
  const ap = data?.agentPrompt || '';
  const colors = (data?.colorPalette?.colors || [])
    .map((c) => `${c.hex} (${c.role})`)
    .join(', ');
  const body = data?.typography?.body?.family || '';
  const display = data?.typography?.display?.family || '';

  return (
    `You are designing a UI in the following identity:\n\n` +
    `Vibe: ${vt.title || ''}\n` +
    `Keywords: ${(vt.keywords || []).join(', ')}\n\n` +
    `Palette: ${colors}\n` +
    `Typography: display=${display}, body=${body}\n\n` +
    `${ap}\n\n` +
    `Follow the Do's and Don'ts above. Output as Figma frames.`
  );
}

function buildStitchPrompt(data) {
  const ap = data?.agentPrompt || '';
  const vt = data?.visualTheme || {};
  return (
    `Generate a UI for this identity using the Stitch DESIGN.md format.\n\n` +
    `Title: ${vt.title || ''}\n` +
    `Atmosphere: ${vt.atmosphere || ''}\n\n` +
    `${ap}`
  );
}


/* ══════════════════════════════════════════
   AI 개발 프롬프트 빌더
   ══════════════════════════════════════════ */

/* -------------------------------------------------
   Cursor Rules (.cursorrules)
   ------------------------------------------------- */
function buildCursorRules(data) {
  if (!data) return '';
  const vt = data?.visualTheme ?? {};
  const cp = data?.colorPalette ?? {};
  const tp = data?.typography ?? {};
  const cm = data?.components ?? {};
  const lo = data?.layout ?? {};
  const ru = data?.rules ?? {};
  const rs = data?.responsive ?? {};

  const lines = [];
  lines.push(`# .cursorrules — ${vt.title || 'TRLOY Design System'}`);
  lines.push(`# Generated by TRLOY · ${todayYMD()}`);
  lines.push('');
  lines.push('## Design Tokens');
  lines.push('');
  lines.push('### Colors (CSS Custom Properties)');
  lines.push('```css');
  lines.push(tokensToCSSVariables(data));
  lines.push('```');
  lines.push('');
  lines.push('### Typography');
  ['display', 'heading', 'body', 'caption'].forEach((role) => {
    const s = tp[role];
    if (!s) return;
    lines.push(`- ${role}: ${s.family || ''}, ${s.size || ''}, weight ${s.weight || ''}, lh ${s.lineHeight || ''}`);
  });
  lines.push('');
  lines.push('### Components');
  ['button', 'input', 'card'].forEach((name) => {
    const c = cm[name];
    if (!c) return;
    lines.push(`- ${name}: ${Object.entries(c).map(([k, v]) => `${k}=${v}`).join(', ')}`);
  });
  lines.push('');
  lines.push('### Layout');
  Object.entries(lo).forEach(([k, v]) => lines.push(`- ${k}: ${v}`));
  lines.push('');
  lines.push('### Responsive Breakpoints');
  (rs.breakpoints || []).forEach((bp) => {
    lines.push(`- ${bp.name || ''}: ${bp.query || ''} (${bp.cols || '?'}col)`);
  });
  lines.push('');
  lines.push("## Do's and Don'ts");
  (ru.dos ?? []).forEach((d) => lines.push(`- DO: ${d}`));
  (ru.donts ?? []).forEach((d) => lines.push(`- DON'T: ${d}`));
  lines.push('');
  lines.push('## Implementation Checklist');
  lines.push('- [ ] Declare color tokens as CSS :root variables');
  lines.push('- [ ] Use Google Fonts or system font fallback');
  lines.push('- [ ] Each section as independent component');
  lines.push('- [ ] Mobile responsive (breakpoint: 768px)');
  lines.push('- [ ] Intersection Observer + CSS transition for interactions');
  lines.push('- [ ] Semantic HTML (section, nav, header, footer)');
  lines.push('- [ ] Accessibility: alt, aria-label');

  return lines.join('\n');
}

/* -------------------------------------------------
   Claude Code 프롬프트
   ------------------------------------------------- */
function buildClaudeCodePrompt(data) {
  if (!data) return '';
  const vt = data?.visualTheme ?? {};
  const cssVars = tokensToCSSVariables(data);
  const tailwind = tokensToTailwindConfig(data);

  return [
    `# Claude Code 실행 프롬프트 — ${vt.title || 'TRLOY Design'}`,
    `생성일: ${todayYMD()}`,
    '',
    '아래 DESIGN.md를 기반으로 Next.js (App Router) 프로젝트를 생성하세요.',
    '',
    `## 토큰\n\`\`\`css\n${cssVars}\n\`\`\``,
    '',
    `## Tailwind 설정\n\`\`\`js\n${tailwind}\n\`\`\``,
    '',
    `## 무드`,
    `Title: ${vt.title || ''}`,
    `Atmosphere: ${vt.atmosphere || ''}`,
    `Keywords: ${(vt.keywords || []).join(', ')}`,
    '',
    '## 폴더 구조',
    '```',
    '/src',
    '  /app',
    '    layout.tsx',
    '    page.tsx',
    '    globals.css  // 위 CSS 변수 포함',
    '  /components',
    '    Hero.tsx',
    '    About.tsx',
    '    Stats.tsx',
    '    Projects.tsx',
    '    CTA.tsx',
    '    Footer.tsx',
    '```',
    '',
    '## 체크리스트',
    '- [ ] 시맨틱 HTML',
    '- [ ] 반응형 (768px 브레이크포인트)',
    '- [ ] 다크 모드 CSS 변수 전환',
    '- [ ] Intersection Observer 스크롤 애니메이션',
    '- [ ] 접근성 (aria-label, alt)',
  ].join('\n');
}


